export const Items = [
	{_id: '1', name: 'adventure hat', price: 50, url: 'http://images.clipartpanda.com/hat-clip-art-nicubunu_Adventurer_hat_Vector_Clipart.png'},
	{_id: '2', name: 'monocle', price: 60, url: 'http://worldartsme.com/images/monocle-clipart-1.jpg'},
	{_id: '3', name: 'sunglasses', price: 20, url: 'http://images.clipartpanda.com/sunglasses-clipart-9TRBdEjTe.svg'},
	{_id: '4', name: 'beard', price: 50, url: 'http://pngimg.com/upload/beard_PNG6258.png'},
	{_id: '5', name: 'round glasses', price: 60, url: 'http://gallery.yopriceville.com/var/albums/Free-Clipart-Pictures/Movember-PNG/Movember_Shades_PNG_PNG_Clipart_Picture.png?m=1438127986'},
	{_id: '6', name: 'baseball cap', price: 20, url: 'http://images.clipartpanda.com/hat-clip-art-pc5bK8McB.png'},
	{_id: '7', name: 'funny glasses', price: 50, url: 'http://images.clipartpanda.com/funny-clip-art-clipart-funny-glasses-512x512-c927.png'},
	{_id: '8', name: 'clown hair', price: 60, url: 'http://worldartsme.com/images/clown-wig-clipart-1.jpg'},
	{_id: '9', name: 'bunny ears', price: 20, url: 'http://cliparts.co/cliparts/8ix/K8b/8ixK8bB8T.png'},
	{_id: '10', name: 'wizard hat', price: 50, url: 'http://cliparts.co/cliparts/5TR/KXo/5TRKXoqLc.jpg'},
	{_id: '11', name: 'spin-top hat', price: 60, url: 'http://cliparts.co/cliparts/8cA/ErE/8cAErEaLi.jpg'},
	{_id: '12', name: 'party hat', price: 20, url: 'http://worldartsme.com/images/party-hat-clipart-1.jpg'},
	{_id: '13', name: 'ray bans', price: 50, url: 'http://images.clipartpanda.com/glasses-clip-art-black-star-glasses.svg'},
	{_id: '14', name: 'aviators', price: 60, url: 'http://static1.squarespace.com/static/5590d298e4b0b23e50b37483/t/55919a7ee4b0f356a27c0115/1435605631217/?format=300w'},
	{_id: '15', name: 'pirate hat', price: 20, url: 'http://www.clker.com/cliparts/x/z/o/A/j/a/pirate-hat-md.png'},
	{_id: '16', name: 'hair bow', price: 50, url: 'http://vignette1.wikia.nocookie.net/clubpenguin/images/1/1f/Pink_Bow_%28Puffle_Hat%29.png/revision/latest?cb=20130807142743&path-prefix=es'},
	//{_id: '17', name: 'bow tie', price: 60, url: 'http://content.mycutegraphics.com/graphics/clothing/black-bow-tie.png'},
	{_id: '18', name: 'viking hat', price: 20, url: 'http://1.bp.blogspot.com/-vHp_C4AzyRU/TexjwodyBII/AAAAAAAAAxQ/LA6h1bEOJXA/s1600/GreenVikingHat.png'},
	{_id: '19', name: 'necktie', price: 50, url: 'http://www.clipartkid.com/images/2/striped-blue-tie-clip-art-8Wub0u-clipart.png'},
	{_id: '20', name: 'construction hat', price: 60, url: 'http://images.clipartpanda.com/construction-worker-hat-clipart-constr-helmet-01.png'},
	{_id: '21', name: 'elvis hair', price: 20, url: 'http://www.datemplate.com/postpic/2014/01/elvis-hair-clip-art_481714.png'},
	{_id: '22', name: 'crown', price: 50, url: 'http://images.clipartpanda.com/crown-clip-art-crown.png'},
	{_id: '23', name: 'googly eyes', price: 60, url: 'http://clipartion.com/wp-content/uploads/2015/11/awesome-googly-eyes-2-quot-stickerswegeling-redbubble-clipart.png'},
	{_id: '24', name: 'angry eyebrows', price: 20, url: 'http://images.easyfreeclipart.com/251/-sunglasses-clip-art-sun-with-stock-vector-cute-funny-251841.png'},
	{_id: '25', name: 'pirate bandana', price: 50, url: 'http://ekladata.com/ZG6qD_mS8MS-ddI22rDGMYE-VG4.png'},
	{_id: '26', name: 'leprechaun hat', price: 60, url: 'http://www.clipartlord.com/wp-content/uploads/2015/03/st-patrick-hat2.png'},
	/*{_id: '27', name: 'sunglasses', price: 20, url: 'http://images.clipartpanda.com/sunglasses-clipart-9TRBdEjTe.svg'},
	{_id: '28', name: 'hat', price: 50, url: 'http://images.clipartpanda.com/hat-clip-art-nicubunu_Adventurer_hat_Vector_Clipart.png'},
	{_id: '29', name: 'monocle', price: 60, url: 'http://worldartsme.com/images/monocle-clipart-1.jpg'},
	{_id: '30', name: 'sunglasses', price: 20, url: 'http://images.clipartpanda.com/sunglasses-clipart-9TRBdEjTe.svg'},
	{_id: '31', name: 'hat', price: 50, url: 'http://images.clipartpanda.com/hat-clip-art-nicubunu_Adventurer_hat_Vector_Clipart.png'},
	{_id: '32', name: 'monocle', price: 60, url: 'http://worldartsme.com/images/monocle-clipart-1.jpg'},
	{_id: '33', name: 'sunglasses', price: 20, url: 'http://images.clipartpanda.com/sunglasses-clipart-9TRBdEjTe.svg'},
	{_id: '34', name: 'hat', price: 50, url: 'http://images.clipartpanda.com/hat-clip-art-nicubunu_Adventurer_hat_Vector_Clipart.png'},
	{_id: '35', name: 'monocle', price: 60, url: 'http://worldartsme.com/images/monocle-clipart-1.jpg'},
	{_id: '36', name: 'sunglasses', price: 20, url: 'http://images.clipartpanda.com/sunglasses-clipart-9TRBdEjTe.svg'}*/
];